### PR TITLE
Move CI to Github Actions

### PR DESCRIPTION
**Pull request by simonihmig**
In preparation for a future Embroider support PR that is expected to add Embroider test scenarios, I wanted to switch to an ember-try based setup. And when doing that, I figured we can move to Github Actions at the same time.

The workflow is based on what my usual setup looks like, but feel free to suggest changes if you want it aligned to other projects or so...

### CODE REVIEW

**Comment by simonihmig** [comment]
Oh, right. @ef4 seems you have to enable GH actions for this repo! (If you agree with the switch here that is)

**Comment by ef4** [comment]
Hmm, they're already allowed. I'll just merge it and see if that kicks it off.

**Comment by simonihmig** [comment]
Yeah, they ran successfully now on master luckily. It makes sense actually, as kicking off new (unapproved) workflows from a fork (giving them access to secrets) would be a security risk. IIRC I have read about related limitations...

**Comment by mansona** [comment]
any secrets are not accessible at all which causes a few problems when working with github actions 🙈  but the limitation here is that you need to commit an empty workflow file to master before PRs will start building 👍 

thanks for doing this work btw 🎉

**Pull request merged**
