### PR TITLE
Adds support to Ember Engines 

### PR DESCRIPTION
**Pull request by villander**
adding `ember-engines` to the `ember-addon.after` array 🎉

### CODE REVIEW

**Comment by ef4** [comment]
Thanks. Could you please merge and release? I just gave you the necessary permissions. This can be v1.0.2. The steps are pretty standard:

1. Update version in package.json.
2. Write something in CHANGELOG.md.
3. Create git tag v1.0.2 and push it to github.
4. Run `npm publish`.

**Comment by villander** [comment]
ok, I'll do it, thanks

**Comment by ef4** [comment]
Thanks!

**Comment by villander** [comment]
published 🎉  https://www.npmjs.com/package/prember

**Pull request merged**
